# Generated by Django 3.2.5 on 2021-07-28 15:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('tag_id', models.CharField(max_length=10000, primary_key=True, serialize=False)),
                ('image_url', models.TextField(blank=True, default='../../static/img/default_no_img.png')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Item_category', to='clothing.clothcategory')),
            ],
        ),
        migrations.CreateModel(
            name='WornEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateField(default=django.utils.timezone.now)),
                ('temperture', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Worn_item', to='clothing.clothingitem')),
            ],
        ),
    ]
